#!/bin/bash
sudo apt update -y
sudo apt install default-jre -y
sudo apt install nfs-common -y
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt update -y
sudo mkdir -p /var/lib/jenkins
sudo mount -t nfs fs-036dc52e8ed9b15f6.efs.us-west-2.amazonaws.com:/ /var/lib/jenkins 
echo "fs-036dc52e8ed9b15f6.efs.us-west-2.amazonaws.com:/ /var/lib/jenkins nfs4 defaults 0 0" | sudo tee -a /etc/fstab 
sudo mount -a
sudo apt install jenkins -y
sudo chown -R jenkins:jenkins /var/lib/jenkins
sudo systemctl start jenkins
